name: "build"

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        macos: [latest, 14, 13, 12]

    runs-on: macos-${{ matrix.macos }}
    name: macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install -f --overwrite scons autoconf automake pkg-config libtool go

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: |
          make

      - name: Install
        run: |
          sudo make install

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]

    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install scons autoconf automake pkg-config libtool go

      - name: Build
        run: |
          make

      - name: Create tarball
        run: |
          make dist

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: roc-vad.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
